"""Tests for the report generator module."""

from datetime import datetime, timezone

from airflow_copilot.models import AnalysisResult, FailureClassification, LLMExplanation
from airflow_copilot.report_generator import generate_report


def _make_result() -> AnalysisResult:
    return AnalysisResult(
        dag_id="test_dag",
        dag_run_id="scheduled__2026-05-25T06:45:00",
        task_id="test_task",
        logical_date=datetime(2026, 5, 25, 6, 45, tzinfo=timezone.utc),
        try_number=1,
        classification=FailureClassification(
            failure_type="sql_error",
            confidence=0.95,
            details={
                "exception_type": "ProgrammingError",
                "sql_error": "column 'market_cap_usd' does not exist",
                "signals_found": {"sql_error": 0.85, "python_exception": 0.5},
            },
        ),
        explanation=LLMExplanation(
            summary="SQL query failed due to missing column.",
            root_cause="The column 'market_cap_usd' was renamed to 'market_cap' in a recent schema change.",
            confidence=0.95,
            remediation_steps=[
                "Update column reference from market_cap_usd to market_cap.",
                "Test the query in a SQL worksheet first.",
            ],
            what_not_to_do=["Do not rename the column back."],
        ),
    )


class TestGenerateReport:
    def test_generates_markdown_with_header(self):
        result = _make_result()
        report = generate_report(result)

        assert report.startswith("# Airflow Failure Report")
        assert "## Summary" in report
        assert "## Failed DAG" in report

    def test_includes_dag_metadata(self):
        result = _make_result()
        report = generate_report(result)

        assert "test_dag" in report
        assert "test_task" in report
        assert "scheduled__2026-05-25T06:45:00" in report
        assert "Try Number | 1" in report

    def test_includes_classification(self):
        result = _make_result()
        report = generate_report(result)

        assert "Sql Error" in report
        assert "95%" in report
        assert "ProgrammingError" in report

    def test_includes_remediation_steps(self):
        result = _make_result()
        report = generate_report(result)

        assert "Update column reference" in report
        assert "Test the query" in report

    def test_includes_what_not_to_do(self):
        result = _make_result()
        report = generate_report(result)

        assert "## What NOT to Do" in report
        assert "Do not rename the column back" in report

    def test_handles_missing_explanation(self):
        result = _make_result()
        result.explanation = None
        report = generate_report(result)

        assert "Analysis pending" in report

    def test_handles_missing_classification(self):
        result = _make_result()
        result.classification = None
        report = generate_report(result)

        assert "Unknown" in report

    def test_includes_footer(self):
        result = _make_result()
        report = generate_report(result)

        assert "dag-doctor" in report
        assert "generated by" in report.lower()

    def test_report_is_readable(self):
        result = _make_result()
        report = generate_report(result)

        # Report should be a valid non-empty markdown string
        assert isinstance(report, str)
        assert len(report) > 200
        assert "# " in report
