"""GitHub integration — create issues from incident reports with dedup."""

from __future__ import annotations

import logging

import httpx

from airflow_copilot.config import get_settings

logger = logging.getLogger(__name__)


def create_github_issue(
    incident: dict,
    token: str | None = None,
    repo: str | None = None,
) -> dict | None:
    """Create a GitHub issue from an incident report. Deduplicates against existing open issues.

    Args:
        incident: AnalysisResult as dict with classification, explanation, evidence.
        token: GitHub personal access token. Falls back to GITHUB_TOKEN env var.
        repo: GitHub repo in owner/name format. Falls back to GITHUB_REPO env var.

    Returns:
        Dict with issue_number and html_url on success, None on failure.
    """
    settings = get_settings()
    gh_token = token or settings.__dict__.get("github_token", "")
    gh_repo = repo or settings.__dict__.get("github_repo", "")

    if not gh_token or not gh_repo:
        logger.warning("GitHub integration not fully configured")
        return None

    classification = incident.get("classification", {}) or {}
    explanation = incident.get("explanation", {}) or {}
    evidence = incident.get("evidence", [])
    failure_type = (
        classification.get("failure_type", "unknown").replace("_", " ").title()
    )
    dag_id = incident.get("dag_id", "unknown")
    task_id = incident.get("task_id", "unknown")

    evidence_text = "\n".join(e.get("source_line", "") for e in (evidence or []))

    title = f"[dag-doctor] {failure_type} in {dag_id}/{task_id}"
    body = (
        f"## dag-doctor Incident Report\n\n"
        f"**DAG:** `{dag_id}`\n"
        f"**Task:** `{task_id}`\n"
        f"**Run:** `{incident.get('dag_run_id', 'N/A')}`\n"
        f"**Severity:** {incident.get('severity', 'medium').upper()}\n\n"
        f"### Root Cause\n{explanation.get('root_cause', 'N/A')}\n\n"
        f"### Evidence\n```\n{evidence_text}\n```\n\n"
        f"### Classification\n- Type: {failure_type}\n"
        f"- Confidence: {classification.get('confidence', 0):.0%}\n\n"
        f"### Remediation\n"
        + "\n".join(f"- {s}" for s in explanation.get("remediation_steps", []))
        + "\n\n> Generated by [dag-doctor](https://github.com/mouadja02/dag-doctor)"
    )
    labels = ["dag-doctor", failure_type.lower().replace(" ", "-")]

    headers = {
        "Authorization": f"Bearer {gh_token}",
        "Accept": "application/vnd.github.v3+json",
        "Content-Type": "application/json",
    }

    api_base = "https://api.github.com"

    try:
        async with httpx.Client(timeout=15.0) as client:
            # Dedup: search for existing open issues with same title
            search_resp = client.get(
                f"{api_base}/search/issues",
                params={
                    "q": f'"{title}" repo:{gh_repo} state:open type:issue in:title'
                },
                headers=headers,
            )
            if search_resp.status_code == 200:
                items = search_resp.json().get("items", [])
                if items:
                    existing = items[0]
                    logger.info(
                        "Duplicate GitHub issue found: %s", existing.get("html_url")
                    )
                    return {
                        "issue_number": existing["number"],
                        "html_url": existing["html_url"],
                        "deduplicated": True,
                    }

            # Create new issue
            resp = client.post(
                f"{api_base}/repos/{gh_repo}/issues",
                json={"title": title, "body": body, "labels": labels},
                headers=headers,
            )
            if resp.status_code in (200, 201):
                data = resp.json()
                return {
                    "issue_number": data["number"],
                    "html_url": data["html_url"],
                    "deduplicated": False,
                }
            else:
                logger.error("GitHub API error %s: %s", resp.status_code, resp.text)
                return None

    except Exception as e:
        logger.error("Failed to create GitHub issue: %s", e)
        return None


def link_to_github(
    token: str | None = None,
    repo: str | None = None,
) -> str | None:
    """Build a GitHub issue creation URL for manual use."""
    settings = get_settings()
    gh_repo = repo or settings.__dict__.get("github_repo", "")
    if not gh_repo:
        return None
    return f"https://github.com/{gh_repo}/issues/new"
