"""Report generator — produces Markdown incident reports from analysis results."""

from __future__ import annotations

from datetime import datetime, timezone

from airflow_copilot.models import AnalysisResult


def generate_report(result: AnalysisResult) -> str:
    """Generate a Markdown incident report from an analysis result."""
    sections = [
        _header(),
        _summary(result),
        _failed_dag_section(result),
        _classification_section(result),
        _evidence_section(result),
        _root_cause_section(result),
        _remediation_section(result),
        _follow_up_section(result),
        _risk_notes_section(),
        _footer(),
    ]
    return "\n\n".join(s for s in sections if s)


def _header() -> str:
    return "# Airflow Failure Report"


def _summary(result: AnalysisResult) -> str:
    if result.classification:
        ftype = result.classification.failure_type.replace("_", " ").title()
    else:
        ftype = "Unknown"

    if result.explanation and result.explanation.summary:
        body = result.explanation.summary
    else:
        body = f"The task `{result.task_id}` in DAG `{result.dag_id}` failed."

    return f"## Summary\n\n**{ftype}**: {body}"


def _failed_dag_section(result: AnalysisResult) -> str:
    logical = result.logical_date.isoformat() if result.logical_date else "N/A"
    return f"""## Failed DAG

| Field | Value |
|-------|-------|
| DAG ID | {result.dag_id} |
| Run ID | {result.dag_run_id} |
| Task ID | {result.task_id} |
| Logical Date | {logical} |
| Try Number | {result.try_number} |"""


def _classification_section(result: AnalysisResult) -> str:
    if not result.classification:
        return ""

    ftype = result.classification.failure_type.replace("_", " ").title()
    conf = result.classification.confidence

    lines = [
        "## Failure Classification",
        "",
        f"- **Type**: {ftype}",
        f"- **Confidence**: {conf:.0%}",
    ]

    details = result.classification.details
    if details:
        ex_type = details.get("exception_type")
        if ex_type:
            lines.append(f"- **Exception**: `{ex_type}`")
        sql_err = details.get("sql_error")
        if sql_err:
            lines.append(f"- **SQL Error**: `{sql_err}`")
        missing = details.get("missing_module")
        if missing:
            lines.append(f"- **Missing Module**: `{missing}`")

    return "\n".join(lines)


def _evidence_section(result: AnalysisResult) -> str:
    return "## Evidence from Logs\n\n```\n[Log analysis performed by dag-doctor rule-based classifier]\n```"


def _root_cause_section(result: AnalysisResult) -> str:
    if result.explanation and result.explanation.root_cause:
        return f"## Likely Root Cause\n\n{result.explanation.root_cause}"
    return "## Likely Root Cause\n\nAnalysis pending. Run the full analysis pipeline to get an LLM-powered root cause explanation."


def _remediation_section(result: AnalysisResult) -> str:
    lines = ["## Suggested Safe Remediation"]
    if result.explanation and result.explanation.remediation_steps:
        for i, step in enumerate(result.explanation.remediation_steps, 1):
            lines.append(f"{i}. {step}")
    else:
        lines.append("\nAnalysis pending.")

    if result.explanation and result.explanation.what_not_to_do:
        lines.append("\n## What NOT to Do")
        for i, step in enumerate(result.explanation.what_not_to_do, 1):
            lines.append(f"- {step}")

    return "\n".join(lines)


def _follow_up_section(result: AnalysisResult) -> str:
    return """## Follow-up Checks

- [ ] Verify the fix works in a staging/dev environment before production
- [ ] Check if other DAGs share the same dependency or query pattern
- [ ] Update monitoring alerts if this failure is recurring
- [ ] Document the fix in the team runbook
"""


def _risk_notes_section() -> str:
    return """## Risk Notes

- This report was generated by dag-doctor using automated log analysis.
- LLM-generated suggestions are for guidance only — always review before applying.
- No Airflow state has been modified during this analysis."""


def _footer() -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return f"---\n\n*Report generated by [dag-doctor](https://github.com/mouadja02/dag-doctor) at {ts}*"
